"""initial

Revision ID: 82a71b5998a3
Revises: 67cd56493c88
Create Date: 2023-06-08 13:36:27.180686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a71b5998a3'
down_revision = '67cd56493c88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
